### ISSUE TITLE
CPAN tester results on 0.07

### ISSUE THREAD

**Issue by ajolma** [ajolma/Geo-GDAL-FFI#27] opened 2018-12-10 05:38 UTC
Geo-GDAL-FFI-0.07:
- amd64-freebsd / 5.26.3:
  - FAIL http://www.cpantesters.org/cpan/report/2ce96814-fb87-11e8-9c58-9b3fce0e3bff 

- amd64-freebsd / 5.28.0:
  - FAIL http://www.cpantesters.org/cpan/report/d38ae97e-fbad-11e8-be2d-f24e63b93138 

- x86_64-linux / 5.26.2:
  - FAIL http://www.cpantesters.org/cpan/report/a710edb4-fb88-11e8-8d79-ad14e066f0a4 

- x86_64-linux / 5.28.0:
  - FAIL http://www.cpantesters.org/cpan/report/a598d690-fb88-11e8-8d79-ad14e066f0a4

**Comment by shawnlaffan** [comment] 2018-12-10 06:05
These all look like issues with getting the dynamic libs from Alien:gdal.

Not sure if it is a system or share install, but it might be worth adding more debugging to the test suite.  Something like this:

```perl
warn 'Alien::gdal install type is: ' . Alien::gdal->install_type;
```

Rebuilding Alien::gdal on each system takes a lot of resources, so I'd like to avoid uploading a new version of it until it's really necessary.

**Comment by shawnlaffan** [comment] 2018-12-10 06:09
The errors are also for Alien::gdal 1.11 and 1.13.  Maybe there is something in that?

**Comment by shawnlaffan** [comment] 2018-12-10 21:48
Alien::gdal prints out its dynamic libs during testing, so we can cross check that way also.  

As one example, the failing BSD rig has dynamic libs for Alien::gdal: http://www.cpantesters.org/cpan/report/81bf8cce-f448-11e8-acc3-94b892bdfc8e

This is during testing, though, and not the final installation location, so maybe something changes?

**Comment by ajolma** [comment] 2018-12-12 05:02
One more http://www.cpantesters.org/cpan/report/17620bc0-fcce-11e8-8354-cb55eff47a06

**Comment by shawnlaffan** [comment] 2018-12-12 05:18
I think we need to instrument the tests to run code like that below and upload a dev release.  

Alien::Base uses FFI::CheckLib to search for dynamic libs, so if a direct call returns an empty list then it is missing a dir in the path or there is an issue with FFI::CheckLib.  

```perl
use FFI::CheckLib qw /find_lib/;

print find_lib (lib => 'gdal');
```

**Comment by shawnlaffan** [comment] 2018-12-13 04:34
It's just speculation, but I wonder if it is due to the ```require Alien::gdal``` call being inside the BEGIN block? 

https://github.com/ajolma/Geo-GDAL-FFI/blob/1867fb1bc977903dffe84b0225d0691c97b79693/lib/Geo/GDAL/FFI.pm#L1458-L1460

I would normally expect this to affect all perl versions, though.

**Comment by shawnlaffan** [comment] 2019-01-02 03:46
I'm getting fails for Alien::freexl which are possibly related.  The dyamic_libs, cflags and libs methods all return empty.    
http://www.cpantesters.org/cpan/report/81a624fc-0e18-11e9-afbf-aec3b07506ca

There are similar failing cases for several other of my alien distros.  

@plicease might have some sense of why an alien that compiles will have empty cflags, dynamic_libs etc.

**Comment by shawnlaffan** [comment] 2019-01-25 11:37
This was possibly caused by incomplete dynamic libs being listed due to dependencies.  

If so then it might be fixed by https://github.com/shawnlaffan/perl-alien-gdal/commit/0b19413df7c93a1f86325acd456ceba31cff6bb7

This is in Alien::gdal 1.15, which is now on cpan.

**Comment by shawnlaffan** [comment] 2022-11-21 08:39
This should be fixed now Alien::gdal updates the rpaths of the dynamic libraries.  
https://github.com/shawnlaffan/perl-alien-gdal/issues/22

**Closed** 2023-01-05 19:30 UTC
